import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';
import Image from 'next/image';
import navlogo from '@/assets/navbar-logo.png';

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body style={{ margin: 0, display: 'flex', flexDirection: 'column', minHeight: '100vh', fontFamily: 'var(--font-geist-sans)' }}>
        <header style={{ height: '72px', borderBottom: '1px solid #eaeaea', backgroundColor: '#fff', position: 'sticky', top: 0, zIndex: 100 }}>
          <div style={{ maxWidth: '1280px', margin: '0 auto', padding: '0 2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', height: '100%' }}>
            <h1 style={{ margin: 0, fontSize: '1.5rem', fontWeight: 800, color: '#d10000', letterSpacing: '-0.5px', height: '100%', display: 'flex', alignItems: 'center' }}>
              <Link href="/" style={{ textDecoration: 'none', color: 'inherit', display: 'inline-flex', alignItems: 'center', height: '100%' }}>
                <Image src={navlogo} alt="MOXVER" width={600} height={120} unoptimized style={{ height: '100%', width: 'auto' }} />
              </Link>
            </h1>
            <nav style={{ display: 'flex', gap: '2rem', alignItems: 'center' }}>
              <Link href="/" style={{ textDecoration: 'none', color: '#1a202c', fontWeight: 600, fontSize: '0.9375rem', transition: 'color 0.2s' }}>Home</Link>
              <Link href="/services" style={{ textDecoration: 'none', color: '#1a202c', fontWeight: 600, fontSize: '0.9375rem', transition: 'color 0.2s' }}>Services</Link>
              <Link href="/leadership" style={{ textDecoration: 'none', color: '#1a202c', fontWeight: 600, fontSize: '0.9375rem', transition: 'color 0.2s' }}>Leadership</Link>
              <Link href="/contact" style={{ padding: '0.625rem 1.25rem', backgroundColor: '#d10000', color: '#fff', textDecoration: 'none', borderRadius: '4px', fontWeight: 700, fontSize: '0.9375rem', transition: 'background-color 0.2s' }}>Contact Us</Link>
            </nav>
          </div>
        </header>

        <main style={{ flex: 1 }}>{children}</main>

        <footer style={{ backgroundColor: '#18181b', color: '#fff', padding: '4rem 2rem 2rem', textAlign: 'center' }}>
          <div style={{ maxWidth: '1200px', margin: '0 auto', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '2rem' }}>
            <h2 style={{ fontSize: '1.75rem', margin: 0, fontWeight: 800, letterSpacing: '-0.5px', color: '#d10000' }}>MOXVER</h2>
            <p style={{ maxWidth: '600px', margin: 0, color: '#a1a1aa', lineHeight: '1.6', fontSize: '0.9375rem' }}>Pioneering technology solutions ranging from enterprise software to disruptive AI, built to future-proof your digital presence.</p>
            <div style={{ display: 'flex', gap: '2rem', padding: '1rem 0', borderTop: '1px solid rgba(255,255,255,0.1)', borderBottom: '1px solid rgba(255,255,255,0.1)', width: '100%', justifyContent: 'center' }}>
              <Link href="/" style={{ color: '#fff', textDecoration: 'none', fontWeight: 500, fontSize: '0.9375rem', transition: 'color 0.2s' }}>Home</Link>
              <Link href="/services" style={{ color: '#fff', textDecoration: 'none', fontWeight: 500, fontSize: '0.9375rem', transition: 'color 0.2s' }}>Services</Link>
              <Link href="/leadership" style={{ color: '#fff', textDecoration: 'none', fontWeight: 500, fontSize: '0.9375rem', transition: 'color 0.2s' }}>Leadership</Link>
              <Link href="/contact" style={{ color: '#fff', textDecoration: 'none', fontWeight: 500, fontSize: '0.9375rem', transition: 'color 0.2s' }}>Contact Us</Link>
            </div>
            <p style={{ margin: 0, color: '#71717a', fontSize: '0.875rem' }}>&copy; {new Date().getFullYear()} MS Group Technology. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
